### PR TITLE
Google sign in working!

### PR DESCRIPTION
**Pull request by emshack**
I've been testing only on iOS so far, haven't yet added the code to make Google Sign In work on android. But it works on iOS!

@collinjackson @efortuna

### CODE REVIEW

**Review by efortuna — APPROVED** [review]
is checking in all of the cocoapods files normal? You would know better than me since you've done more flutter development.

**Comment by collinjackson** [comment]
It is probably better to .gitignore them. They aren't needed to build the app, and make it harder to see what changed in the app.

**Comment by emshack** [comment]
So, to be clear, we're talking about .gitignoring everything in the ios/Pods/ directory?

**Review by collinjackson — APPROVED** [review]

**Comment by efortuna** [comment]
Works for me. I defer to you on what the standard practice for doing this is.

**Pull request merged**
