### PR TITLE
Make meme dialog more generic

### PR DESCRIPTION
**Pull request by collinjackson**
The main thing I'm changing here is that I'm making the meme screen into a full-screen dialog that returns the text in its call to Navigator.pop(). This keeps all the Firebase uploading logic to one place in main.dart. I got rid of the ability to change the photo in the meme dialog; instead you have to dismiss the dialog to change the picture.

To avoid the flash of unstyled content while the image upload happens, the dialog loads the image from file instead of the network (uploading happens in the background). We could also download the network image before adding it to the ListView, so that it will instantly lay out in the ListView correctly. It's not clear to me what the cleanest way to do that is, but I can look into it if you want.

### CODE REVIEW

**Review by emshack — CHANGES_REQUESTED** [review]
I'm seeing a couple issues here:
-If I hit cancel from the meme dialog instead of send, it sends my picture anyway, but without any text I may have added. I would expect the picture to not get sent at all.
-Once I have entered into the meme dialog once, every subsequent time, the picture displayed there is the picture from the first time I was in the dialog (though when I hit send, the correct picture is sent).

**Comment by collinjackson** [comment]
Thanks for testing this out. I pushed a fix for the first thing, PTAL. The second fix requires us to randomize the name of the temporary file when picking an image, which I'll do in the image_picker plugin.

**Review by emshack — APPROVED** [review]

**Comment by emshack** [comment]
LGTM, pending the image_picker change!

**Comment by collinjackson** [comment]
once the image picker fix in flutter/image_picker#3 is landed, try flutter packages upgrade

**Pull request merged**
